version: '3'

services:

    scraper:
        build: .
        command: ./bin/deploy
        env_file:
            - ./.env
        links:
            - selenium
        volumes:
            - .:/home

    selenium:
        image: selenium/standalone-chrome:4.0.0-alpha-7-prerelease-20201009
        ports:
            - 4444
        volumes:
            - /dev/shm:/dev/shm
